services:
  psql_bp:
    image: postgres:latest
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - psql_volume_bp:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis_cache
    restart: unless-stopped
    command: ["redis-server", "--requirepass", "${REDIS_PASS}"]
    ports:
      - "${REDIS_PORT}:6379"

volumes:
  psql_volume_bp:
